# Generated by Django 3.2.1 on 2022-03-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactordata',
            name='force',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='charactordata',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
